<?php

namespace AdminBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends EntityRepository
{
    public function produitsvalide($e){
        $req=$this->getEntityManager()
            ->createQuery("select u from UserBundle:produit u WHERE u.status=:e")
            ->setParameter('e',$e);
       return $req->getResult();
    }
}
