<?php

namespace AdminBundle\Repository;

/**
 * transporteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class transporteurRepository extends \Doctrine\ORM\EntityRepository
{
}
