<?php

namespace UserBundle\Repository;

/**
 * CadeauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadeauRepository extends \Doctrine\ORM\EntityRepository
{
}
